# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: ngProjects
  type: object
  default:
    - project: 'project-a'
      build: false
      test: false
      publishTestResults: true
      deployToOcto: true
    - project: 'project-b'
      build: false
      test: false
      publishTestResults: false
      deployToOcto: true

trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  displayName: 'Install NodeJS'
  inputs:
    versionSpec: '14.15.5'
- script: |
    node build-script.js
  displayName: 'Check Commit Message for Project Filter'
  env:
    ${{ each value in parameters.ngProjects }}:
      ${{ format('NG_PROJECT_{0}', upper(value.project)) }}: ${{ value.project }}
    BUILD_COMMIT_MESSAGE: $(Build.SourceVersionMessage)
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install Project Dependencies'
- task: UseGitVersion@5
  displayName: Git Version (SemVer)
  inputs:
    versionSpec: '5.x'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
- ${{ each value in parameters.ngProjects }}:
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'project/$(value.project)'
      customCommand: 'version --new-version  $(GitVersion.SemVer)'
    displayName: 'Git Version (SemVer) Project - ${{ value.project }}'
  - script: |
      ng build ${{ value.project }} --prod
    displayName: 'Building Project - ${{ value.project }}'
    enabled: false
    condition: and(contains(variables.NG_PROJECTS, '${{ value.project }}'), ${{ value.build }})
  - script: | 
      ng test ${{ value.project }} --browsers=ChromeHeadless --code-coverage --progress=false --watch=false 
    displayName: 'Test Project - ${{ value.project }}'
    enabled: false
    condition: and(contains(variables.NG_PROJECTS, '${{ value.project }}'), ${{ value.test }})
