# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  ngProjects:
  - project: 'project-a'
    build: true
  - project: 'project-b'
    build: false

trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
    inputs:
    versionSpec: '10.x'
    displayName: 'Install Node.js'
- script: |
    node build-script.js
  env:
    ngProjects: ${{ parameters.ngProjects }}
- ${{ each value in parameters.ngProjects }}:
  - script: echo ${{ value.project }}