# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: listOfStrings
  type: object
  default:
  - one-a
  - two-b

trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- ${{ each value in parameters.listOfStrings }}:
  - script: echo ${{ value }}