# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  enabled: true
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

#- bash: |
#    echo "##vso[task.setvariable variable=sauce]crushed tomatoes"
#  displayName: 'Set environment variables'

#- script: |
#    node build.js
#  displayName: 'Set environment variables'

#- bash: |
#    echo "my environment variable is $SAUCE"
#  displayName: 'Echo set environment variables'

- bash: |
    echo "##vso[task.setvariable variable=sauce]crushed tomatoes"

# An environment variable called `SAUCE` has been added to all downstream steps
- bash: |
    echo "my environment variable is $SAUCE"

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  enabled: false  
  displayName: 'npm install and build'

- task: YarnInstaller@3
  enabled: false
  inputs:
    versionSpec: '1.x'
    
- task: UseGitVersion@5
  enabled: false
  inputs:
    versionSpec: '5.x'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'