# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: ngProjects
  type: object
  default:
    - project: 'project-a'
      build: true
      test: true
      publishTestResults: true
      deployToOcto: true
    - project: 'project-b'
      build: true
      test: false
      publishTestResults: false
      deployToOcto: true

trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.15.5'
- script: |
    node build-script.js
  env:
    NG_PROJECTS: ${{ join(';',parameters.ngProjects) }}
    BUILD_COMMIT_MESSAGE: $(Build.SourceVersionMessage)
- ${{ each value in parameters.ngProjects }}:
  - script: echo ${{ value.project }}
