# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: ngProjects
  type: object
  default:
    - project: 'project-a'
      build: true
      test: true
      publishTestResults: false
      deployToOcto: true
    - project: 'project-b'
      build: true
      test: true
      publishTestResults: false
      deployToOcto: true

trigger:
- main

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  displayName: 'Install NodeJS'
  inputs:
    versionSpec: '14.15.5'
- script: |
    git config user.email 'coach1001@gmail.com' 
    git config user.name 'Francois Weber'
  displayName: 'Set Git Identity'  
- script: |
    node build-script.js
  displayName: 'Check Commit Message for Project Filter'
  env:
    ${{ each value in parameters.ngProjects }}:
      ${{ format('NG_PROJECT_{0}', upper(value.project)) }}: ${{ value.project }}
    BUILD_COMMIT_MESSAGE: $(Build.SourceVersionMessage)
- script: |
    npm install -g @angular/cli
  displayName: 'Install Angular CLI'
- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'Install Project Dependencies'
- task: UseGitVersion@5
  displayName: Git Version (SemVer)
  inputs:
    versionSpec: '5.x'
    useConfigFile: true
    configFilePath: 'GitVersion.yml'
- ${{ each value in parameters.ngProjects }}:
  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: 'projects/${{ value.project }}'
      customCommand: 'version --new-version --allow-same-version $(GitVersion.SemVer)'
    displayName: 'Git Version (SemVer) Project - ${{ value.project }}'
  - script: |
      ng build ${{ value.project }} --prod
    displayName: 'Building Project - ${{ value.project }}'
    condition: and(contains(variables.NG_PROJECTS, '${{ value.project }}'), ${{ value.build }})
  - script: | 
      ng test ${{ value.project }} --browsers=ChromeHeadless --code-coverage --progress=false --watch=false 
    displayName: 'Test Project - ${{ value.project }}'
    condition: and(contains(variables.NG_PROJECTS, '${{ value.project }}'), ${{ value.test }})
  - task: OctopusPack@4
    inputs:
      packageId: 'Project.${{ value.project }}'
      packageFormat: 'NuPkg'
      packageVersion: '$(GitVersion.NuGetVersion)'
      sourcePath: 'dist/${{ value.project }}'
      outputPath: '$(Build.ArtifactStagingDirectory)'
      nuGetAuthor: 'Francois Weber'
      nuGetTitle: 'Octo Package - ${{ value.project }} $(GitVersion.NuGetVersion)'
    displayName: 'Octo Package Project - ${{ value.project }}'